### ISSUE TITLE
notifyItemChanged() question

### ISSUE THREAD

**Issue by kmare** [thorbenprimke/realm-recyclerview#2]
hello thorbenprimke, 
first of all thank you for your great work, I'm quite new to realm and your library is working quite well for me.
I was wondering if when editing an item I'm supposed to be using notifyItemChanged() (like I would do normally) or there is a better way to do it. Without it the item isn't refreshed automatically.

**Comment by thorbenprimke** [comment]
@kmare - Yes, it should update but because I'm only diffing on the item's id (primary key) which I'm assuming remains the same in your case and thus the `notifyItemChanged` is not triggered.

If you have automatic updates enabled, then whenever the Realm changes the update is received by the adapter. In order to filter out updates not related to the Realm in the adapter, I'm using the ids to detect change and trigger the animations. 
I need to see about an efficient way to detect the change when an item's id is the same but the contents are changed. Maybe hashCode could help.

**Comment by thorbenprimke** [comment]
Committed 49a7a34

**Comment by thorbenprimke** [comment]
@kmare - I added a new optional parameter to the adapter to specify a columnName that should be used for the "id" that is used for diffing the realm changes. 
I tried hashCode but that didn't work because the hashCode didn't change when making an update to a Realm object. It also cannot be overriden to have a custom hashCode. 

I updated the LinearLayout example so that if you long press a row, it updates the text and this triggers the automatic update and `notifyItemChanged` for that item.

**Comment by thorbenprimke** [comment]
resolved 49a7a34

**Comment by kmare** [comment]
Hi @thorbenprimke , thank you for working on this. I implemented what you said, but I think it's not the right way to do it (I might be totally wrong of course and didn't understand exactly what to do). I'll try to explain using your example: so if set the "quote" column to the adapter, it works. But that means that if I have more fields in my model that might change, the notifyItemChanged() won't be called on them. So I believe what's needed to be set in the adapter is actually the "id" (PrimaryKey) which remains constant and any change made to any other field should trigger the notifyItemChanged().
Not sure I explained properly the issue.

**Comment by thorbenprimke** [comment]
Yes, you should ideally have a column that would change whenever anything on the object changes.

Since posting my last response, I actually changed it back to always use the primaryKey and have an optional second column (202b59028a09a922e83d28ea7ed716e28bb8ba98). 
In the example, I'm using "quote" for the optional column. 

However, in a real application, it probably should be something like "lastChangedTime". This way it is guaranteed that the row changed is detected. 

I hope this clears up any confusion. The whole "keeping track of the ids" is simply to work around the fact that the realm change notifications don't include any information on what has changed. Once this is fixed / added, the "ids" and "diff code" can be removed.

**Comment by kmare** [comment]
You're totally right, didn't realize the adapter parameter was about the second optional column (seemed weird at first, I should have looked at the code a bit more).
Thank you!

**Comment by thorbenprimke** [comment]
No, worries. Thanks for raising this issue initially.
