### ISSUE TITLE
EmptyLayout issues while using Footers and/or Headers

### ISSUE THREAD

**Issue by usernotnull** [thorbenprimke/realm-recyclerview#56]
While using Footers (by addFooter):
The emptyLayout is never shown even when list size is 0.

Another issue I found is when using **Headers**.
If the list starts from 0 objects and I add objects, let's say by pressing a button, the view does not update and remains empty (with or without an emptyLayout). But when i close and reopen that activity, the list populates, and if we start from a list that already has objects in it, there is no problem. But if I call mRealm.delete(Object.class) and start adding again, the same problems occurs and nothing populates.

**Comment by RJFares** [comment]
Another issue I found is when using Headers.
If the list has no objects and starts from emptyLayout, and I add a realm object, the recyclerview does not update and only shows that emptyLayout. (This problem does not happen if headers are not used)

**Comment by cwalmsley** [comment]
For the second issue (the empty view not being removed when the RealmRecyclerView goes from 0 -> 1 objects), I can confirm from my tests that View.GONE is being set correctly (see snippet below) but for some reason it does not hide the view in the UI. I'm still trying to figure out what is causing this.

```
 private void updateEmptyContentContainerVisibility(RecyclerView.Adapter adapter) {
    if (emptyViewId == 0) {
        return;
    }
    emptyContentContainer.setVisibility(
            adapter.getItemCount() == 0 ? View.VISIBLE : View.GONE);
}
```

**Comment by cwalmsley** [comment]
Unfortunately I have not been able to find a solution for this yet.

I've checked that the snippet above runs on the UI thread (it does) and also I've tried clearing any animations on the view as these coukd interfere with View.GONE

The issue is only for type LinearLayoutWithHeaders (and footers). I can't really see what is causing this bug comparing it with the other layout types.

Any help (or pointers of other things for me to try) would be greatly appreciated as currently this bug is a blocker for me to release an app using this feature.

**Comment by JM-Agrimap** [comment]
The problem is in RealmBasedRecyclerViewAdapter, it is caused by updateRowWrappers() not being called by the RealmBasedRecyclerViewAdapter  if there are no ids in the collection.

To fix them problem requires a small change in the method **getRealmChangeListener()**

The following code should be change from

```
return new RealmChangeListener<OrderedRealmCollection<T>>() {
    @Override
    public void onChange(OrderedRealmCollection<T> element) {
        if (animateResults && ids != null && !ids.isEmpty()) {
        updateRowWrappers();
            ...
        } else {
    ...
        }
    }
    ...
}
```

to

```
return new RealmChangeListener<OrderedRealmCollection<T>>() {
    @Override
    public void onChange(OrderedRealmCollection<T> element) {
        updateRowWrappers();

        if (animateResults && ids != null && !ids.isEmpty()) {
            ...
        } else {
    ...
        }
    }
    ...
}
```
