### ISSUE TITLE
How can we get the LayoutManager?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [thorbenprimke/realm-recyclerview#89]
Hi, 

Thanks for creating this library!

I want to get the LayoutManager that is attached with RealmRecyclerView? Is it possible?

My goal is to get callback every time the user reaches the bottom of the list. I see that there is setonLoadMoreListener but it is not working when i reach the bottom. 

```
mRecyclerView.setOnLoadMoreListener(new RealmRecyclerView.OnLoadMoreListener() {
            @Override
            public void onLoadMore(Object o) {
                Log.i("", "");
            }
        });

```

Any solution or suggestion?

**Comment by Pururun** [comment]
`realmRecyclerView.getRecycleView().getLayoutManager()` should work.

**Comment by garfieldcoked** [comment]
@Shajeel-Afzal 

I had a similar issue a few days ago. To achieve your goal of having the load more listener triggered you have to do two things:
1. Ensure that load more is enabled.
   `mRecyclerView.enableShowLoadMore();`
2. After loadMore method is triggered, you have to reset the loadMore has fired using. Do this each time until there are no more results to load. At this point i disable show load more
   `mRecyclerView.resetHasLoadMoreFired();`

For number 2, I added a comment to a merge that addressed this issue because I am not sure this is the correct appraoch, but thats how i got it to work. https://github.com/thorbenprimke/realm-recyclerview/commit/9c8ba1f44a9b4621a0ed778c5c4246137273354b
